oasisprotocol/oasis-rosetta-gateway

- Makefile
- docker/Dockerfile
- docker/README.md
- docker/config.yml
- go.mod
- main.go
- oasis-client/oasis-client.go
- services/block.go
- services/errors.go
- services/network.go
- tests/test.sh
> Use GetStatus

- Makefile
- docker/Dockerfile
- go.mod
- oasis-client/oasis-client.go
- services/account.go
- services/block.go
- services/construction.go
- tests/test-staking-genesis.json
- tests/test.sh
Closes #6.
There were changes in the staking address format and the staking
event structure field names.
> Bump oasis-core version to 20.8

- tests/test.sh
works around the way it runs forever
fixes #28
> run rosetta-cli check:construction in CI

- Makefile
- go.mod
- services/account.go
- services/block.go
- services/common.go
- services/construction.go
- services/errors.go
- services/network.go
- tests/check-prep/main.go
- tests/common/common.go
- tests/construction-signing/main.go
- tests/construction-txtypes/main.go
- tests/test.sh
here's changes for rosetta-cli 0.4.0. it's gonna be an awkward battle to get this integrated
fixes #25
cross-reference #23
> rosetta-cli 0.4.0 and construction tests

- Makefile
- go.mod
- main.go
- services/account.go
- services/block.go
- services/common.go
- services/construction.go
- services/errors.go
- services/network.go
- testclient/main.go
- tests/check-prep/main.go
- tests/common/common.go
- tests/construction-signing/main.go
- tests/construction-txtypes/main.go
- tests/test.sh
based on #22 
closes #22 because it includes that
> Construction API work

- services/common.go
- services/construction.go
- tests/check-prep/main.go
- tests/construction-signing/main.go
- tests/construction-txtypes/main.go
would fix #27 
in this PR:
> increase the complexity of construction to handle the absent fee operation
but it's kind of a lazy conversion, and you can't specify a gas limit because it only looks in the fee transfer metadata for that option.
> construction support for zero-fee transactions

- Makefile
- docker/Dockerfile
- go.mod
- oasis-client/oasis-client.go
- services/block.go
- services/construction.go
- tests/construction-txtypes/main.go
- tests/test-fixture-config.json
- tests/test.sh
> Bump oasis-core version to 20.9

- oasis-client/oasis-client.go
- services/construction.go
fixes #24 
switch to this new API in 20.9
> construction: switch to SubmitTxNoWait

- services/construction.go
- services/errors.go
example of an error reported this way:
> {Code:15 Message:unable to submit transaction Retriable:false Details:map[cause:map[code:1 module:consensus/transaction msg:transaction: invalid nonce]]}
> construction: add cause from oasis to submit error

- services/network.go
Here's one of the simpler options we considered. Might want to revisit this later if we learn about other uses of the genesis_block_identifier field.
> network: suppress missing hash when genesis block is pruned

- Makefile
- docker/Dockerfile
- go.mod
- go.sum
- services/network.go
depends https://github.com/oasisprotocol/oasis-core/pull/3362
fixes #57 
we updated oasis-core to report the pruning status. this adds that to the network status response
> network: provide oldest block identifier in status

- oasis-client/oasis-client.go
- services/account.go
for #61
This takes an unsophisticated approach. Load the delegations and debonding delegations from the existing staking API and put them into the metadata area under new keys. The format that they're in is fine as is.
Also add info about the breakdown of the escrow balance into active and debonding pools and info about the shares.
A preview, where the test entity has delegated 2,000 base units to the testing destination account:
The test entity's (oasis1qzzd6khm3acqskpxlk9vd5044cmmcce78y5l6000) escrow account
```json
{
"block_identifier": {
"index": 175, 
"hash": "8472f4494618356dcfa346a52c1f15f90277470409977018b4f11134c0908715"
}, 
"balances": [
{
"value": "100000000000", 
"currency": {
"symbol": "ROSE", 
"decimals": 9
}
}
], 
"metadata": {
"active_balance": "100000000000", …
```
> put delegations into escrow account metadata

- Makefile
- docker/Dockerfile
- go.mod
- go.sum
- oasis-client/oasis-client.go
- services/network.go
- tests/test.sh
> oasis-client: Handle initial block heights > 1

- README.md
the gas limit is read as a number https://github.com/oasisprotocol/oasis-core-rosetta-gateway/blob/ed23e7eb4ef78183002cdcc5bcc79bdfd6ac1204/services/operations.go#L317
> docs: don't stringify gas limit

- .changelog/122.internal.1.md
- .changelog/122.internal.2.md
- .changelog/122.internal.3.md
- .changelog/122.process.md
- .punch_config.py
- .punch_version.py
- Makefile
- common.mk
- docs/versioning.md
Use Punch tool for tracking and bumping project's version.
Part of #55.
> Define and automate project's versioning

- LICENSE
this came up when we were adding a license to oasis-sdk in https://github.com/oasisprotocol/oasis-sdk/pull/6
> restore template in license

- .changelog/180.internal.md
- oasis/oasis.go
> oasis: Use GetChainContext method instead of fetching genesis document

- .changelog/196.bugfix.md
- oasis/oasis.go
Fixes #196 
Note that the genesis height update is not needed in `GetStatus` as it is already updated during `connect`.
> Fix possible nil pointer dereference in GetStatus

- docs/release-process.md
Apparently, Git has a limitation where if branch named `b` exists, no branch named `b/something` can be created:
https://stackoverflow.com/a/22630664/1872673.
Hence, if branch named `stable/1.5.x` exists, one is unable to create a `stable/1.5.x/backport-foo` or `stable/1.5.x/changelog` branch.
> docs: Avoid / in backport/changelog git branch names in Release Process docs

- .changelog/251.internal.1.md
- .changelog/251.internal.2.md
- .github/workflows/ci-lint.yml
- .github/workflows/ci-tests.yaml
- .github/workflows/release.yml
- CHANGELOG.md
- Makefile
- docker/Dockerfile
- go.mod
~~This is currently blocked by bumping rosetta-cli to a newer version that works with Go 1.16.~~
Resolved in #261.
> Bump Go to version 1.17

- .changelog/278.feature.md
- docker/service/node/run
this is only an optimization. we recommend that users don't rely on software configuration to operate offline.
> docker: skip running node if offline var is set

- .changelog/281.breaking.md
- .github/workflows/docker.yml
- .github/workflows/release.yml
- .gitignore
- .goreleaser.yml
- CHANGELOG.md
- Makefile
- README.md
- common.mk
- common/version.go
- docker/Dockerfile
- docker/README.md
- docker/service/gateway/run
- docs/release-process.md
- docs/versioning.md
- go.mod
- main.go
- services/account.go
- services/block.go
- services/common.go
- services/construction.go
- services/mempool.go
- services/network.go
- tests/check-prep/main.go
- tests/common/common.go
- tests/construction-signing/main.go
- tests/construction-txtypes/main.go
- tests/test.sh
- towncrier.toml
> Rename project to Oasis Rosetta Gateway

- .changelog/330.feature.md
- Makefile
- docker/Dockerfile
- go.mod
- go.sum
21.3.13 has new fields in the status structure. updating the oasis-core module to match
> stable - Bump Oasis Core to 21.3.13

- .changelog/428.internal.md
- .github/workflows/ci-lint.yml
- README.md
markdownlint-cli now requires node 14+
https://github.com/igorshubovych/markdownlint-cli/releases/tag/v0.32.0
> ci: bump Node.js

- .changelog/444.internal.md
- .changelog/445.internal.md
- .changelog/449.internal.go
- .changelog/451.internal.md
- .changelog/452.internal.md
- .changelog/455.feature.md
- .punch_version.py
- CHANGELOG.md
this is for us to release a docker image with oasis-core 22.2.11
> Assemble changes for 2.5.0 release

- .changelog/480.internal.md
- .github/workflows/ci-lint.yml
Keep CI alive while we do not have Towncrier fork updated
sample issue from other repo https://github.com/oasisprotocol/oasis-wallet-web/actions/runs/6692075152/job/18180527014?pr=1747.
See https://github.com/oasisprotocol/oasis-core/pull/5421.
> Install setuptools to make Towncrier fork work with Python 3.12

- .changelog/328.doc.md
- docs/release-process.md
fixes #322 
let's change these so that we don't have to fiddle with the protected branch settings
> docs: change suggested backport branch names

- .changelog/487.doc.md
- CHANGELOG.md
- README.md
- docker/.dockerignore
- docker/README.md
- services/account.go
- services/construction.go
- @gw0 pointed out that docs now recommend /node/data and /node/etc. here's at least an explanation of what we do differently
- all of our links now redirect, so I went through
- omg rosetta's website is moving, and they no longer have api structure reference
> docs: updates

- .changelog/507.internal.md
- .gitignore
- Makefile
Coinbase has silently renamed Rosetta-related repos to "mesh." Here's a patch to fix our build.
No further renaming until they at least acknowledge the renaming.
> tests: rosetta -> mesh

- .changelog/524.doc.md
- README.md
they reinstated these in their new docs site
> docs: restore specific model refrence links

- .changelog/527.internal.md
- .github/workflows/ci-dependabot.yml
- .github/workflows/ci-lint.yml
- command injection through PR title
- switch over to shell variable substitution in certain places that used command string interpolation
- switch to a default environment variable https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables in a place where we defined our own
> CI: fix command injection plus other changes

- .changelog/535.trivial.md
- .github/workflows/ci-dependabot.yml
Converting all `${{ github.` into env variables
> Harden github workflow against injection
