oasisprotocol/oasis-rosetta-gateway

.github/workflows/ci.yaml
=> Add CI using GitHub Actions

Makefile, README.md, docker/Dockerfile, docker/README.md, go.mod, main.go, oasis-client/oasis-client.go, services/account.go, services/block.go, services/common.go, services/construction.go, services/network.go
=> Bump oasis-core version to 20.7

Makefile, go.mod, main.go, services/account.go, services/block.go, services/construction.go, services/network.go
=> Bump rosetta-sdk-go version to 0.2.0

tests/test.sh
it is conjectured that this tests more, but it's not stated what more this tests
cross reference https://github.com/oasisprotocol/oasis-core-rosetta-gateway/pull/31#discussion_r466888805
=> tests: run multiple transactions

oasis-client/oasis-client.go, services/block.go, services/construction.go, tests/construction-txtypes/main.go
in this design, we use zero-amount operations to create an intent, and we add code to emit that intent when we observe a reclaim escrow transaction.
=> construction: add reclaim escrow

.github/workflows/ci.yaml, README.md
=> Add more documentation

README.md
=> network-specific docs for block API

Makefile, docker/Dockerfile, go.mod, go.sum, services/construction.go
fixes #39 
:sparkles: `errors.Is` :sparkles:
=> construction: treat already-in-mempool as success

main.go, oasis-client/oasis-client.go, services/errors.go, services/mempool.go, services/operations.go, tests/construction-signing/main.go
=> services: Add support for the mempool endpoints

README.md, main.go, services/common.go, services/construction.go, services/errors.go, tests/test.sh
=> Support offline mode for construction API

.changelog/138.internal.1.md, .changelog/138.internal.2.md, .changelog/138.internal.3.md, .changelog/55.process.md, .github/workflows/release.yml, .gitignore, .goreleaser.yml, Makefile, README.md, common.mk, docs/release-process.md
=> Define and automate release process

.changelog/188.feature.md, oasis/oasis.go, services/block.go
=> Add epoch number to block metadata

.changelog/290.feature.md, .punch_version.py, CHANGELOG.md
=> Assemble changes for 2.1.0 release

.changelog/310.trivial.md, .github/CODEOWNERS
gonna be approving some dependabot things along with this new oasis-core upgrade
=> github: add me to codeowners

.changelog/286.internal.md, .changelog/287.internal.md, .changelog/293.internal.md, .changelog/295.internal.md, .changelog/304.internal.md, .changelog/305.internal.md, .changelog/310.trivial.md, .changelog/311.internal.md, .changelog/312.feature.md, .changelog/314.internal.md, .punch_version.py, CHANGELOG.md
so we can get testnet nodes running again!
=> Assemble changes for 2.2.0 release

.changelog/318.feature.2.md, .changelog/325.feature.md
we're adding this entry in #323, here's a copy for the master branch
=> changelog: add missing note

.changelog/318.feature.md, .changelog/323.feature.md, Makefile, docker/Dockerfile, go.mod, go.sum
=> backport - Bump Oasis Core to 22.1.3

.changelog/318.feature.md, .changelog/323.feature.md, .punch_version.py, CHANGELOG.md
=> Assemble changes for 2.2.1 release

.changelog/424.doc.md, README.md
(reopening from #425 so we don't have to force push to their master branch)
=> fixed error on Reclaim Escrow documentation

.changelog/436.internal.md, .github/workflows/ci-dependabot.yml
samples https://github.com/buberdds/oasis-rosetta-gateway/pulls
=> Append change log fragment to Dependabot PR

.changelog/405.internal.md, .changelog/409.internal.md, .changelog/412.internal.md, .changelog/413.internal.md, .changelog/417.internal.md, .changelog/418.internal.md, .changelog/424.doc.md, .changelog/428.internal.md, .changelog/430.internal.md, .changelog/432.internal.md, .changelog/433.feature.md, .changelog/434.internal.md, .changelog/435.internal.md, .changelog/436.internal.md, .changelog/437.internal.md, .changelog/438.feature.md, .punch_version.py, CHANGELOG.md
so we can get the middleware version feature out to our partners who want it
=>  Assemble changes for 2.4.0 release

.changelog/457.internal.md, .changelog/459.internal.md, .changelog/460.internal.md, .changelog/463.internal.md, .changelog/465.internal.md, .changelog/470.internal.md, .changelog/471.internal.md, .changelog/472.internal.md, .changelog/474.feature.md, .punch_version.py, CHANGELOG.md
=> Assemble changes for 2.6.0 release

.changelog/486.feature.md, docker/Dockerfile, docker/config-testnet.yml
- testnet genesis file
- config migration
- bump docker base images
=> docker: testnet genesis and other updates

.changelog/488.feature.md, docker/config.yml
=> docker: migrate mainnet config

.changelog/491.feature.md, docker/Dockerfile
=> docker: update mainnet genesis

.changelog/.markdownlint.yml, .changelog/506.internal.md, .gitlint, .markdownlint.yml
CI is failing 
```
*** Building rosetta-cli...
bash: line 1: cd: tests/rosetta-cli-0.10.3: No such file or directory
```
=> Update gitlint and markdownlint configs
